# Generated by Django 6.0 on 2026-03-05 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("bd_models", "0014_alter_ball_options_alter_ballinstance_options_and_more")]

    operations = [
        migrations.CreateModel(
            name="EventBall",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text=(
                            "Start time of the eventball. When active, all countryballs of this type become eventballs."
                        )
                    ),
                ),
                ("end_date", models.DateTimeField(help_text="End time of the eventball.")),
                (
                    "catch_phrase",
                    models.CharField(
                        blank=True,
                        help_text="Sentence sent in bonus when someone catches a eventball",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "capacity_name",
                    models.CharField(
                        blank=True, help_text="Name of the eventball's capacity", max_length=64, null=True
                    ),
                ),
                (
                    "capacity_description",
                    models.CharField(
                        blank=True, help_text="Description of the countryball's capacity", max_length=256, null=True
                    ),
                ),
                (
                    "wild_card",
                    models.ImageField(
                        blank=True,
                        help_text="An optional wild card for this eventball.",
                        max_length=200,
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "collection_card",
                    models.ImageField(
                        blank=True,
                        help_text="An optional collection card for this eventball.",
                        max_length=200,
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "credits",
                    models.CharField(
                        blank=True, help_text="Author of the collection artwork", max_length=64, null=True
                    ),
                ),
                (
                    "ball",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="eventballs", to="bd_models.ball"
                    ),
                ),
                (
                    "regime",
                    models.ForeignKey(
                        blank=True,
                        help_text="An optional regime for this eventball.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bd_models.regime",
                    ),
                ),
            ],
            options={"verbose_name_plural": "eventballs", "db_table": "eventball", "managed": True},
        ),
        migrations.CreateModel(
            name="EventBallInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "ball_instance",
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="bd_models.ballinstance"
                    ),
                ),
                (
                    "event_ball",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="eventballs.eventball"),
                ),
                ("player", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bd_models.player")),
            ],
            options={"db_table": "eventballinstance", "managed": True},
        ),
    ]
