# Generated by Django 6.0 on 2026-03-05 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bd_models", "0014_alter_ball_options_alter_ballinstance_options_and_more"),
        ("eventballs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventballinstance",
            name="ball_instance",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventball",
                to="bd_models.ballinstance",
            ),
        )
    ]
