# Generated by Django 5.2.8 on 2026-05-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventball_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventball',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='eventball',
            name='emoji_id',
            field=models.BigIntegerField(default=0, help_text='Emoji ID of this eventball.'),
        ),
    ]
